
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  username:
  password: ubuntu
  host: localhost
  database: your-pc-store-db

test:
  <<: *default
  database: your-pc-store-db

production:
  <<: *default
  url: postgres://_your_pc_store:O2qMiwfQaw0GgrlwRNcFAlQYutx5Yk25@dpg-cntd1lvjbltc739a0p7g-a/your_pc_store_db
  host: <%= ENV["DATABASE_HOST"] %>
  database: <%= ENV["RAILS_DB_NAME"] %>
  username: <%= ENV["RAILS_DB_USERNAME"] %>
  password: <%= ENV["RAILS_DB_PASSWORD"] %>
