
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: ubuntu
  password: ubuntu

development:
  <<: *default
  database: your-pc-store-db

test:
  <<: *default
  database: your-pc-store-db

production:
  host: <%= ENV["DATABASE_HOST"] %>
  database: <%= ENV["RAILS_DB_NAME"] %>
  username: <%= ENV["RAILS_DB_USERNAME"] %>
  password: <%= ENV["RAILS_DB_PASSWORD"] %>
